import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Navbar from "@/shared/components/Navbar";
import "bootstrap-icons/font/bootstrap-icons.css";
import { ThemeProvider } from "next-themes";
import { NavbarProvider } from "@/shared/context/NavbarContext";
import { WidthProvider } from "@/shared/context/WidthContext";
import AuxNavbar from "@/features/property-filter/components/AuxNavbar";
import Providers from "@/shared/components/Providers";
import ConditionalNavbars from "@/shared/components/ConditionalNavbars";
import { WishlistProvider } from "@/features/wishlist/context/WishlistContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Airbnb - Home",
  description: "Generated by create next app",
};
export const dynamic = "force-dynamic";
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="">
        <ThemeProvider attribute="class">
          <Providers>
            <WishlistProvider>
            <NavbarProvider>
              <WidthProvider>
                <ConditionalNavbars>
                  <Navbar />
                  <AuxNavbar />
                </ConditionalNavbars>
                <div className="main">{children}</div>
              </WidthProvider>
            </NavbarProvider>
            </WishlistProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
