import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Navbar from "../components/header/navbar/Navbar";
import "bootstrap-icons/font/bootstrap-icons.css";
import { ThemeProvider } from "next-themes";
import { NavbarProvider } from "@/context/navbarContext/NavbarContext";
import { WidthProvider } from "@/context/width/WidthContext";
import AuxNavbar from "@/components/header/auxNavbar/AuxNavbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Airbnb - Home",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="">
        <ThemeProvider attribute="class">
          <NavbarProvider>
            <WidthProvider>
              <Navbar />
              <AuxNavbar />
              <div className="main">{children}</div>
            </WidthProvider>
          </NavbarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
